spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:deliveryslots}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:deliveryslots}
    password: ${DB_PASS:deliveryslots}

  h2:
    console:
      enabled: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect